/**
 * 2026-02-28T17:00:00+08:00: Phase A2 - businessType 对标 ABCPOS 7 种 Business Type
 * Enterprise | Fine Dining | Casual Dining | QSR | Cafe/Tea | Retail | Bakery
 */
const VERTICAL_TEMPLATE_VERSION = "2026-02-24-v1";

const VERTICAL_TEMPLATES = Object.freeze([
  {
    templateCode: "MILK_TEA",
    displayName: "奶茶店",
    displayNameEn: "Milk Tea",
    businessType: "CAFE_TEA",
    typeGroup: "QSR_BEVERAGE",
    supportedCountries: ["US", "CA", "IE", "GB"],
    operatingModes: ["TAKEAWAY", "DELIVERY", "SELF_PICKUP"],
    requiredCapabilities: [
      "COUNTER_CHECKOUT",
      "EMV_NFC_PAYMENT",
      "FRONT_RECEIPT_PRINT",
      "QUEUE_CALLING",
      "MENU_AD_SIGNAGE",
    ],
    recommendedCapabilities: ["SELF_ORDER_KIOSK", "KITCHEN_TICKET_PRINT"],
    menuOptionProfile: {
      optionModel: "MULTI_MODIFIER",
      examples: ["糖度", "冰量", "加料", "杯型"],
      highFrequencyEdits: true,
    },
    tableServiceProfile: {
      enabled: false,
    },
  },
  {
    templateCode: "SUSHI",
    displayName: "寿司",
    displayNameEn: "Sushi",
    businessType: "CASUAL_DINING",
    typeGroup: "DINE_IN_LIGHT",
    supportedCountries: ["US", "CA", "IE", "GB"],
    operatingModes: ["DINE_IN", "TAKEAWAY", "DELIVERY"],
    requiredCapabilities: [
      "COUNTER_CHECKOUT",
      "TABLESIDE_ORDERING",
      "KDS_PRODUCTION",
      "KITCHEN_TICKET_PRINT",
      "EMV_NFC_PAYMENT",
    ],
    recommendedCapabilities: ["CUSTOMER_FACING_DISPLAY", "OFFLINE_TOLERANCE"],
    menuOptionProfile: {
      optionModel: "COMBO_AND_MODIFIER",
      examples: ["套餐", "加料", "辣度", "规格"],
      highFrequencyEdits: true,
    },
    tableServiceProfile: {
      enabled: true,
      supportsSeatSplit: true,
      supportsCourseControl: true,
    },
  },
  {
    templateCode: "DIM_SUM",
    displayName: "广式早茶",
    displayNameEn: "Dim Sum",
    businessType: "CASUAL_DINING",
    typeGroup: "DINE_IN_FULL",
    supportedCountries: ["US", "CA", "IE", "GB"],
    operatingModes: ["DINE_IN", "TAKEAWAY"],
    requiredCapabilities: [
      "COUNTER_CHECKOUT",
      "TABLESIDE_ORDERING",
      "KDS_PRODUCTION",
      "KITCHEN_TICKET_PRINT",
      "FRONT_RECEIPT_PRINT",
      "EMV_NFC_PAYMENT",
    ],
    recommendedCapabilities: ["CASH_MANAGEMENT", "CUSTOMER_FACING_DISPLAY"],
    menuOptionProfile: {
      optionModel: "SMALL_PLATE_MULTI_ROUND",
      examples: ["加点", "并台", "席位分单"],
      highFrequencyEdits: true,
    },
    tableServiceProfile: {
      enabled: true,
      supportsSeatSplit: true,
      supportsTableMerge: true,
    },
  },
  {
    templateCode: "WESTERN_DINING",
    displayName: "西餐",
    displayNameEn: "Western Dining",
    businessType: "FINE_DINING",
    typeGroup: "DINE_IN_FULL",
    supportedCountries: ["US", "CA", "IE", "GB", "FR", "ES", "NL"],
    operatingModes: ["DINE_IN", "TAKEAWAY", "DELIVERY"],
    requiredCapabilities: [
      "COUNTER_CHECKOUT",
      "TABLESIDE_ORDERING",
      "KDS_PRODUCTION",
      "EMV_NFC_PAYMENT",
      "FRONT_RECEIPT_PRINT",
    ],
    recommendedCapabilities: ["CUSTOMER_FACING_DISPLAY", "CASH_MANAGEMENT", "OFFLINE_TOLERANCE"],
    menuOptionProfile: {
      optionModel: "COURSE_AND_MODIFIER",
      examples: ["前菜/主菜/甜点", "熟度", "配菜替换"],
      highFrequencyEdits: false,
    },
    tableServiceProfile: {
      enabled: true,
      supportsSeatSplit: true,
      supportsCourseControl: true,
    },
  },
  {
    templateCode: "CHINESE_FAST_FOOD",
    displayName: "中式快餐",
    displayNameEn: "Chinese Fast Food",
    businessType: "QSR",
    typeGroup: "QSR_FOOD",
    supportedCountries: ["US", "CA", "IE", "GB"],
    operatingModes: ["TAKEAWAY", "DELIVERY", "SELF_PICKUP", "DINE_IN"],
    requiredCapabilities: [
      "COUNTER_CHECKOUT",
      "EMV_NFC_PAYMENT",
      "KITCHEN_TICKET_PRINT",
      "KDS_PRODUCTION",
      "QUEUE_CALLING",
    ],
    recommendedCapabilities: ["SELF_ORDER_KIOSK", "MENU_AD_SIGNAGE"],
    menuOptionProfile: {
      optionModel: "FAST_COMBO",
      examples: ["套餐", "单点", "加料", "备注"],
      highFrequencyEdits: true,
    },
    tableServiceProfile: {
      enabled: true,
      supportsSeatSplit: false,
    },
  },
  {
    templateCode: "NAIL_SALON",
    displayName: "美甲店",
    displayNameEn: "Nail Salon",
    businessType: "ENTERPRISE",
    typeGroup: "SERVICE",
    supportedCountries: ["US", "CA", "IE", "GB", "FR", "ES", "NL"],
    operatingModes: ["APPOINTMENT", "WALK_IN"],
    requiredCapabilities: [
      "COUNTER_CHECKOUT",
      "EMV_NFC_PAYMENT",
      "FRONT_RECEIPT_PRINT",
    ],
    recommendedCapabilities: ["CUSTOMER_FACING_DISPLAY", "CASH_MANAGEMENT"],
    menuOptionProfile: {
      optionModel: "SERVICE_PACKAGE",
      examples: ["服务时长", "技师偏好", "附加项目"],
      highFrequencyEdits: false,
    },
    tableServiceProfile: {
      enabled: false,
    },
  },
  {
    templateCode: "HOTPOT",
    displayName: "火锅店",
    displayNameEn: "Hotpot",
    businessType: "CASUAL_DINING",
    typeGroup: "DINE_IN_FULL",
    supportedCountries: ["US", "CA", "IE", "GB"],
    operatingModes: ["DINE_IN", "TAKEAWAY"],
    requiredCapabilities: [
      "COUNTER_CHECKOUT",
      "TABLESIDE_ORDERING",
      "KDS_PRODUCTION",
      "KITCHEN_TICKET_PRINT",
      "EMV_NFC_PAYMENT",
      "FRONT_RECEIPT_PRINT",
    ],
    recommendedCapabilities: ["CASH_MANAGEMENT", "OFFLINE_TOLERANCE"],
    menuOptionProfile: {
      optionModel: "BASE_AND_MULTI_ROUND",
      examples: ["锅底", "蘸料", "多轮加单", "席位分账"],
      highFrequencyEdits: true,
    },
    tableServiceProfile: {
      enabled: true,
      supportsSeatSplit: true,
      supportsTableMerge: true,
      supportsLongSession: true,
    },
  },
  {
    templateCode: "CAFE",
    displayName: "咖啡馆",
    displayNameEn: "Cafe",
    businessType: "CAFE_TEA",
    typeGroup: "QSR_BEVERAGE",
    supportedCountries: ["US", "CA", "IE", "GB", "FR", "ES", "NL"],
    operatingModes: ["DINE_IN", "TAKEAWAY", "SELF_PICKUP"],
    requiredCapabilities: ["COUNTER_CHECKOUT", "EMV_NFC_PAYMENT", "FRONT_RECEIPT_PRINT"],
    recommendedCapabilities: ["SELF_ORDER_KIOSK", "KITCHEN_TICKET_PRINT"],
    menuOptionProfile: {
      optionModel: "MULTI_MODIFIER",
      examples: ["杯型", "浓度", "糖浆", "奶"],
      highFrequencyEdits: true,
    },
    tableServiceProfile: { enabled: true, supportsSeatSplit: false },
  },
  {
    templateCode: "RETAIL",
    displayName: "零售",
    displayNameEn: "Retail",
    businessType: "RETAIL",
    typeGroup: "RETAIL",
    supportedCountries: ["US", "CA", "IE", "GB"],
    operatingModes: ["WALK_IN", "SELF_PICKUP"],
    requiredCapabilities: ["COUNTER_CHECKOUT", "EMV_NFC_PAYMENT", "FRONT_RECEIPT_PRINT"],
    recommendedCapabilities: ["INVENTORY_TRACKING", "BARCODE_SCAN"],
    menuOptionProfile: {
      optionModel: "SIMPLE_ITEM",
      examples: ["规格", "数量"],
      highFrequencyEdits: false,
    },
    tableServiceProfile: { enabled: false },
  },
  {
    templateCode: "BAKERY",
    displayName: "烘焙店",
    displayNameEn: "Bakery",
    businessType: "BAKERY",
    typeGroup: "QSR_FOOD",
    supportedCountries: ["US", "CA", "IE", "GB"],
    operatingModes: ["TAKEAWAY", "DINE_IN", "SELF_PICKUP"],
    requiredCapabilities: ["COUNTER_CHECKOUT", "EMV_NFC_PAYMENT", "FRONT_RECEIPT_PRINT"],
    recommendedCapabilities: ["SCALE_WEIGHT", "KITCHEN_TICKET_PRINT"],
    menuOptionProfile: {
      optionModel: "MULTI_MODIFIER",
      examples: ["规格", "切片", "数量"],
      highFrequencyEdits: true,
    },
    tableServiceProfile: { enabled: false },
  },
]);

module.exports = {
  VERTICAL_TEMPLATE_VERSION,
  VERTICAL_TEMPLATES,
};
